{% set name = "libmongocxx" %}
{% set version = "4.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mongodb/mongo-cxx-driver/releases/download/r{{ version }}/mongo-cxx-driver-r{{ version }}.tar.gz
  sha256: affa1163821cde865be2ba46e5d8348d87d4b47eb181b021455a1b4b7b7261f6

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake <4
    - ninja
  host:
    - libboost-headers
    - libbson
    - libmongoc

test:
  commands:
    - test -f ${PREFIX}/include/mongocxx/v_noabi/mongocxx/client.hpp    # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/libmongocxx.pc         # [unix]
    - test -f ${PREFIX}/lib/libmongocxx${SHLIB_EXT}          # [unix]
    - if not exist %LIBRARY_INC%\mongocxx\v_noabi\mongocxx\client.hpp (exit 1)     # [win]
    - if not exist %LIBRARY_LIB%\mongocxx-v_noabi-rhi-md.lib (exit 1)    # [win]
    - if not exist %LIBRARY_BIN%\mongocxx-v_noabi-rhi-md.dll (exit 1)    # [win]

about:
  home: https://github.com/mongodb/mongo-cxx-driver
  license: Apache-2.0
  license_file: LICENSE
  summary: The mongocxx is a ground-up rewrite of a C++ driver for MongoDB based on libmongoc.

extra:
  recipe-maintainers:
    - Tobias-Fischer
